[package]
name = "mpc-contract"
version = "0.1.0"
authors = ["Near Inc <hello@nearprotocol.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
near-sdk = { path = "../../near-sdk" }
hex = "0.4"

[dev-dependencies]
near-workspaces = { version = "0.16.0", features = ["unstable"] }
tokio = { version = "1.14", features = ["full"] }
mpc-contract = { path = "." }

[profile.release]
codegen-units = 1
# Tell `rustc` to optimize for small code size.
opt-level = "z"
lto = true
debug = false
panic = "abort"
