language: rust
rust:
  - stable
  - nightly
env:
  - NEAR_RELEASE=true
  - NEAR_RELEASE=false

matrix:
  include:
  - name: "Compile examples"
    rust: nightly
    before_script:
      - rustup target add wasm32-unknown-unknown
    script:
      - ./examples/check_all.sh

branches:
  only:
  - master

script:
  - ./ci-test.sh
  - ./examples/test_all.sh
