language: rust
rust:
  - stable
  - nightly-2019-09-03
env:
  - NEAR_RELEASE=true
  - NEAR_RELEASE=false

matrix:
  allow_failures:
    - rust: nightly-2019-09-03
  fast_finish: true

before_install:
  - rm rust-toolchain

before_script:
  - rustup target add wasm32-unknown-unknown

branches:
  only:
  - master

script:
  - ./ci-test.sh
