language: rust
rust:
  - nightly
env:
  - NEAR_RELEASE=true
  - NEAR_RELEASE=false

matrix:
  before_script: rustup target add wasm32-unknown-unknown
  fast_finish: true

branches:
  only:
  - master

script:
  - ./ci-test.sh